ALTER TABLE flashcards
ADD COLUMN next_review_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN stability FLOAT DEFAULT 0,
ADD COLUMN difficulty FLOAT DEFAULT 0,
ADD COLUMN state VARCHAR(20) DEFAULT 'New',
ADD COLUMN last_review_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN review_count INTEGER DEFAULT 0,
ADD COLUMN lapses INTEGER DEFAULT 0; 